services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: bio-tracker-api
    container_name: bio-tracker-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bio-tracker-network

  web:
    image: nginx:alpine
    container_name: bio-tracker-web
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bio-tracker-network

  db:
    image: postgres:16-alpine
    container_name: bio-tracker-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bio_tracker
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - bio-tracker-network

  redis:
    image: redis:alpine
    container_name: bio-tracker-redis
    restart: unless-stopped
    tty: true
    networks:
      - bio-tracker-network

networks:
  bio-tracker-network:
    driver: bridge
